services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    environment:
      - URLS_PRIMARY_NAME=agent
      - "URLS=[{ url: 'docs/openapi.yaml', name: 'agent' }]"
      - SUPPORTED_SUBMIT_METHODS=['get', 'post', 'update', 'delete', 'put']
    volumes:
      - ./docs:/usr/share/nginx/html/docs

  db:
    image: mysql:8.0.22
    container_name: mysql_boot
    hostname: mysql_boot
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tableOrderDB
      MYSQL_ROOT_PASSWORD: toor
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      - ./db/mysql/config:/etc/mysql/conf.d