services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    environment:
      - URLS_PRIMARY_NAME=agent
      - "URLS=[{ url: 'docs/openapi.yaml', name: 'agent' }]"
      - SUPPORTED_SUBMIT_METHODS=['get']
    volumes:
      - ./docs:/usr/share/nginx/html/docs