server:
  port: ${PORT:8000}

spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:${DB_URL_SCHEMA:mysql}://${DB_HOST:0.0.0.0}:${DB_PORT:3306}/${DB_NAME:testDB}?useSSL=${DB_SSL:false}&allowPublicKeyRetrieval=true
    username: ${DB_USER:testDB}
    password: ${DB_PASSWORD:testPW}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  cors:
    allowed_origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8081}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace